<item>
    <title>[[+title:cdata]]</title>
    <link>[[+url]]</link>
    <description>[[+excerpt:cdata]]</description>
    <author>[[+author]]</author>
    <category>[[+category_name:cdata]]</category>
    <comments>[[+url]]</comments>
    <pubDate>[[+createdon]]</pubDate>
    <guid>[[+url]]</guid>
</item>